name: iban_form_field
description: An IBAN form which deals with spacing and country specific rules.
version: 0.1.1
author: inapay POS authors <info@inapay.com>
homepage: https://github.com/inapay/iban_form_field

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  iban: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  flutter_test:
    sdk: flutter

